/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculatePayout' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [
        IDL.Record({
          'tourDays' : IDL.Nat,
          'grossSalary' : IDL.Float64,
          'workingDays' : IDL.Nat,
          'sundayOvertimes' : IDL.Nat,
          'leaveDays' : IDL.Nat,
          'payout' : IDL.Float64,
        }),
      ],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMonthAttendance' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'getSalary' : IDL.Func([], [IDL.Float64], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAttendance' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'setAttendance' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'setSalary' : IDL.Func([IDL.Float64], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculatePayout' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [
          IDL.Record({
            'tourDays' : IDL.Nat,
            'grossSalary' : IDL.Float64,
            'workingDays' : IDL.Nat,
            'sundayOvertimes' : IDL.Nat,
            'leaveDays' : IDL.Nat,
            'payout' : IDL.Float64,
          }),
        ],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMonthAttendance' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'getSalary' : IDL.Func([], [IDL.Float64], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAttendance' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'setAttendance' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'setSalary' : IDL.Func([IDL.Float64], [], []),
  });
};

export const init = ({ IDL }) => { return []; };